---
- name: integration of terraform and ansible
  hosts: all
  become: true

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: installing apache2
      package:
        name: apache2
        state: present

    - name: installing php
      package:
        name: php
        state: present

    - name: starting apache2 service
      service:
        name: apache2
        state: started
        enabled: true

    - name: installing git
      package:
        name: git
        state: present

    - name: making folder
      file:
        path: /var/www/html/web
        state: directory
        mode: '0755'

- name: Copy Website files to AWS EC2
      ansible.builtin.copy:
        src: ./website/
        dest: /var/www/html/
        mode: '0755'
